import ReduxProvider from '@/components/ReduxProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Weather Pwa',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {apple: '/icon.png'},
  themeColor: '#3B97D3'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-full min-h-screen overflow-x-hidden bg-gray-800'>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
